---
- hosts: localhost
  become: true
  become_user: root
  gather_facts: no
  vars:
      repo_initials: imv
      git_repo_url: https://github.com/sufius/imv-landau.git
      repo_path: /var/www/imv-Landau
      repo_branch: main
      user: vagrant
      home_path: /home/vagrant
  tasks:
    - name: Run the equivalent of "apt-get update" as a separate step
      apt:
        upgrade: "yes"
        update_cache: yes

    - name: Download Node.js setup script
      get_url: url=https://deb.nodesource.com/setup_14.x dest=/opt mode=755

    - name: Setup Node.js
      command: /opt/setup_14.x
      changed_when: false

    - name: Install required packages
      apt:
        name: ['htop', 'git', 'curl', 'wget', 'nginx', 'nodejs']
        state: present

    - name: "Install NPM-distributed command-line tools"
      npm:
        global: yes
        name: "{{ item }}"
      with_items:
        - pm2
        - '@vue/cli'

    - name: Clone a private repository
      git:
       repo: "{{ git_repo_url }}"
       dest: "{{ repo_path }}"
       version: "{{ repo_branch }}"
       accept_hostkey: yes
       force: yes

    - name: Create node_modules directory in home
      file:
        path: "{{ home_path }}/{{ repo_initials }}_node_modules"
        state: directory

    - name: Create node_modules directory in {{ repo_path }}
      file:
        path: "{{ repo_path }}/node_modules"
        state: directory

    - name: Mount node_modules directory to
      become_user: {{ user }}
      ansible.posix.mount:
        path: "{{ home_path }}/{{ repo_initials }}_node_modules"
        src: "{{ repo_path }}/node_modules"
        opts: rw,nodev,relatime,iocharset=utf8,uid=1000,gid=1000,_netdev
        state: mounted
        fstype: vboxsf

    - name: Install packages based on package.json using the npm
      npm:
        path: "{{ repo_path }}"
        state: present

    - name: Build app
      command: npm run build
      changed_when: false
      args:
        chdir: "{{ repo_path }}"
