---
- hosts: localhost
  become: true
  become_user: root
  gather_facts: no
  vars:
      repo_initials: imv
      git_repo_url: https://github.com/sufius/imv-landau.git
      repo_path: /var/www/imv-landau
      repo_branch: main
      user: vagrant
      home_path: /home/vagrant
  tasks:
    - name: "********* apt-get update *********"
      apt:
        upgrade: "yes"
        update_cache: yes

    - name: "********* download nodejs *********"
      get_url: url=https://deb.nodesource.com/setup_14.x dest=/opt mode=755

    - name: "********* setup nodejs *********"
      command: /opt/setup_14.x
      changed_when: false

    - name: "********* apt install ... *********"
      apt:
        name: ['htop', 'git', 'curl', 'wget', 'nginx', 'nodejs']
        state: present

    - name: "********* npm install -g ... *********"
      npm:
        global: yes
        name: "{{ item }}"
      with_items:
        - pm2
        - '@vue/cli'

    - name: "********* create node_modules directory in home *********"
      become: true
      become_user: "{{ user }}"
      file:
        path: "{{ home_path }}/{{ repo_initials }}_node_modules"
        state: directory

    - name: "********* create node_modules directory in {{ repo_path }} *********"
      file:
        path: "{{ repo_path }}/node_modules"
        state: directory

    - name: "********* mount node_modules directory to {{ home_path }}/{{ repo_initials }}_node_modules *********"
      mount:
        path: "{{ repo_path }}/node_modules"
        src: "{{ home_path }}/{{ repo_initials }}_node_modules"
        opts: bind,rw
        state: mounted
        fstype: none

    - name: "********* npm install *********"
      npm:
        path: "{{ repo_path }}"
        state: present

    - name: "********* npm run build *********"
      command: npm run build
      changed_when: false
      args:
        chdir: "{{ repo_path }}"
