---
- name: Install Nginx web server
  become: true
  apt:
    name: nginx
    state: latest
  notify: Restart Nginx

- name: Add nginx.api.conf template file to the Nginx available sites
  become: true
  template:
    src: templates/nginx.api.conf
    dest: "/etc/nginx/sites-available/{{ server_name }}.conf"
  notify: Restart Nginx

- name: Enable nginx.api.conf template file as an available site of Nginx
  become: true
  file:
    src: "/etc/nginx/sites-available/{{ server_name }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ server_name }}.conf"
    state: link
  notify: Restart Nginx

- name: Add enabled Nginx site to /etc/hosts
  become: true
  lineinfile:
    path: /etc/hosts
    regexp: "{{ server_name }}"
    line: "127.0.0.1 {{ server_name }}"
