---
- hosts: all
  become: true
  gather_facts: true # (we don't need to check the connectivity between master and other nodes)

  pre_tasks:
    - name: Update apt cache.
      become: true
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false

    - name: Upgrade apt packages
      become: true
      apt:
        upgrade: dist

    - name: "Install apt packages"
      become: true
      apt:
        name: "{{ apt_packages }}"
        state: latest

    - name: Set bashrc files
      import_tasks: tasks/bashrc.yml

  tasks:
    - name: Install NGINX
      include_role:
        name: nginxinc.nginx
      vars:
        nginx_debug_output: true
        nginx_logrotate_conf_enable: true
        nginx_logrotate_conf:
          paths:
            - /var/log/nginx/*.log
          options:
            - daily
            - missingok
            - rotate 14
            - compress
            - delaycompress
            - notifempty
            - sharedscripts

    - include_role:
        name: nginxinc.nginx_config
      vars:
        nginx_config_http_template_enable: true
        nginx_config_http_template:
          - template_file: http/default.conf.j2
            conf_file_name: 50_example.com.conf
            conf_file_location: /etc/nginx/conf.d/

            servers:
              - listen:
                  - ip: 0.0.0.0
                    port: 80

                  - ip: 0.0.0.0
                    port: 443
                    ssl: true

                server_name: example.com
                error_page: /usr/share/nginx/html
                autoindex: false
                http_demo_conf: false

                access_log:
                  - name: json
                    location: /var/log/nginx/example.com-access.json.log
                error_log:
                  level: warn
                  location: /var/log/nginx/example.com-error.log

                locations:
                  - location: /
                    proxy_pass: http://127.0.0.1
                    proxy:
                      bind: false
                      set_header:
                        - field: Host
                          value: $host
                        - field: X-Forwarded-For
                          value: $proxy_add_x_forwarded_for
                        - field: X-Real-IP
                          value: $remote_addr
                        - field: REMOTE_ADDR
                          value: $remote_addr

    - name: Prepare to install the correct PHP version
      include_role:
        name: geerlingguy.php-versions

    - name: Install PHP
      include_role:
        name: geerlingguy.php

    - name: Install composer
      include_role:
        name: geerlingguy.composer
