---
- hosts: all
  become: true
  gather_facts: true # (we don't need to check the connectivity between master and other nodes)

  pre_tasks:
    - name: Update apt cache.
      become: true
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false

    - name: Upgrade apt packages
      become: true
      apt:
        upgrade: dist

    - name: "Install apt packages"
      become: true
      apt:
        name: "{{ apt_packages }}"
        state: present

    - name: Set bashrc files
      import_tasks: tasks/bashrc.yml

  tasks:
    - name: Prepare to install the correct PHP version
      import_role:
        name: geerlingguy.php-versions
      tags: php

    - name: Install PHP
      import_role:
        name: geerlingguy.php
      tags: php

    - name: Install NGINX
      include_role:
        name: geerlingguy.nginx
      vars:
        nginx_remove_default_vhost: true
        nginx_user: "{{ user }}"
        ### necessary for vue but already activated by default
        # nginx_extra_http_options: |
        #   include  /etc/nginx/mime.types;
        #   default_type  application/octet-stream;
        nginx_vhosts:
          - listen: "80"
            server_name: _  # (unused but playbook crashes without it)
            filename: "client.{{ domain }}.conf"
            root: "{{ client_public_path }}"
            ### recommended by laravel, but has to be added/set by app
            # add_header: "X-Frame-Options \"SAMEORIGIN\""
            # add_header: "X-Content-Type-Options \"nosniff\""
            # charset: "utf-8"
            state: "present"
            extra_parameters: |
              location /api {
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header Host $host;
                proxy_pass http://127.0.0.1:85;
              }
              location / {
                  root {{ client_public_path }};
                  index index.html;
                  try_files $uri $uri/ /index.html;
              }
              location = /favicon.ico { access_log off; log_not_found off; }
              location = /robots.txt  { access_log off; log_not_found off; }
              location ~ /\.(?!well-known).* {
                  deny all;
              }
              location = /50x.html {
                root /usr/share/nginx/html;
              }
            error_page: "500 502 503 504  /50x.html"
            access_log: "/var/log/nginx/{{ domain }}.log"
            error_log: "/var/log/nginx/{{ domain }}-error.log"
          - listen: "85"
            server_name: _  # (unused but playbook crashes without it)
            filename: "api.{{ domain }}.conf"
            root: "{{ api_public_path }}"
            index: "index.php index.html index.htm"
            state: "present"
            extra_parameters: |
              location / {
                try_files $uri $uri/ /index.php?$query_string;
              }
              location ~ \.php$ {
                  fastcgi_pass 127.0.0.1:9000;
                  fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
                  include fastcgi_params;
              }
            access_log: "/var/log/nginx/{{ domain }}.log"
            error_log: "/var/log/nginx/{{ domain }}-error.log"
            error_page: "404 /index.php"

    - name: Install composer
      include_role:
        name: geerlingguy.composer
