---
- hosts: all
  become: true
  gather_facts: true # (we don't need to check the connectivity between master and other nodes)

  pre_tasks:
    - name: Update apt cache.
      become: true
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false

    - name: Upgrade apt packages
      become: true
      apt:
        upgrade: dist

    - name: "Install apt packages"
      become: true
      apt:
        name: "{{ apt_packages }}"
        state: latest

    - name: Set bashrc files
      import_tasks: tasks/bashrc.yml

  tasks:
    - name: Install NGINX
      include_role:
        name: nginx

    - name: Prepare to install the correct PHP version
      import_role:
        name: geerlingguy.php-versions
      tags: php

    - name: Install PHP
      import_role:
        name: geerlingguy.php
      tags: php

    # - name: Install composer
    #   include_role:
    #     name: geerlingguy.composer
