---
- hosts: all
  become: true
  gather_facts: true # (we don't need to check the connectivity between master and other nodes)

  tasks:
    - name: Install nodejs
      import_role:
        name: geerlingguy.nodejs
      tags: nodejs

    - name: Install pm2
      npm:
         name: "{{ item }}"
         global: yes
      with_items: "{{ npm_packages | flatten(1) }}"

    - name: Install npm packages
      npm:
        path: "{{ client_root_path }}"
        executable: /usr/bin/npm

    - name: "Run npm with: {{ npm_run_command }}"
      command: "{{ npm_run_command }}"
      args:
        chdir: "{{ client_root_path }}"
      when: env == "prod"

#    - name: "Run npm with: {{ npm_run_command }}"
#      shell: "nohup {{ npm_run_command }} </dev/null >/dev/null 2>&1 &"
#      args:
#        chdir: "{{ client_root_path }}"
#      register: npm_output
#
#
#    - name: Write npm output to file
#      copy:
#        content: "{{ npm_output.stdout }}"
#        dest: "../npm-debug.log"
#
#    - debug:
#        var: npm_output.stdout