---
- hosts: localhost
  become: true
  become_user: root
  gather_facts: no # (we don't need to check the connectivity between master and other nodes)
  vars:
      user: vagrant
      home_path: /home/vagrant
      project_path: /var/www/imv-landau
      project_initials: imv
      apt_packages:
        - "htop"
        - "git"
        - "curl"
        - "wget"
        - "nginx"
        - "nodejs"
      npm_packages:
        - "pm2"
        - "@vue/cli"
      bashrc_lines:
        - "alias ll='ls -haltr'"
        - "alias ..='cd ..'"
        - "alias ...='cd ../..'"
        - "alias imv='cd /var/www/imv-landau'"
        - "alias www='cd /var/www/imv-landau'"

  tasks:
    - name: "********* apt-get update *********"
      apt:
        upgrade: "yes"
        update_cache: yes

    - name: "Add alias for {{ user }}"
      lineinfile:
        path="{{ home_path }}/.bashrc"
        line="{{ item }}"
        owner="{{ user }}"
        regexp="{{ item }}"
        state=present
        insertafter=EOF
        create=True
      with_items: "{{ bashrc_lines }}"

    - name: "Source alias for {{ user }}"
      shell: "source {{ home_path }}/.bashrc"

    - name: "********* download nodejs *********"
      get_url: url=https://deb.nodesource.com/setup_14.x dest=/opt mode=755

    - name: "********* setup nodejs *********"
      command: /opt/setup_14.x
      changed_when: false

    - name: "********* apt install ... *********"
      apt:
        name: "{{ apt_packages }}"
        state: present

    - name: "********* npm install -g ... *********"
      npm:
        global: yes
        name: "{{ npm_packages }}"

    - name: "********* create node_modules directory in home *********"
      become: true
      become_user: "{{ user }}"
      file:
        path: "{{ home_path }}/{{ project_initials }}_node_modules"
        state: directory

    - name: "********* create node_modules directory in {{ project_path }} *********"
      file:
        path: "{{ project_path }}/node_modules"
        state: directory

    - name: "********* mount node_modules directory to {{ home_path }}/{{ project_initials }}_node_modules *********"
      mount:
        path: "{{ project_path }}/node_modules"
        src: "{{ home_path }}/{{ project_initials }}_node_modules"
        opts: bind,rw
        state: mounted
        fstype: none

    - name: "********* npm install *********"
      npm:
        path: "{{ project_path }}"
        state: present

    # - name: "********* npm run build *********"
    #   command: npm run build
    #   changed_when: false
    #   args:
    #     chdir: "{{ project_path }}"

    - name: "********* start server *********"
      command: npm run serve
      changed_when: false
      args:
        chdir: "{{ project_path }}"
